//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessUygulamasi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AntrenmanKayitlari
    {
        public int kayitID { get; set; }
        public int antrenmanID { get; set; }
        public int hareketID { get; set; }
        public int hareketSira { get; set; }
    }
}
